apiVersion: v1
kind: Service
metadata:
  labels:
    app: employee-service
  name: employee-service
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: employee-app
