apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
        - env:
            - name: MONGO_DB_URL
              value: mongodb://employee-mongo:27017/employees
          image: kuyseng/employee_app
          name: employee-app
          ports:
            - containerPort: 3000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: employee-app
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: employee-app

