apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      db: employee-mongo
  template:
    metadata:
      labels:
        db: employee-mongo
    spec:
      containers:
        - image: mongo
          name: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongodb
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongo-volume-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: employee-mongo
spec:
  selector:
    db: employee-mongo
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017