version: '1'
services:
  app:
    image: kuyseng/employee_app
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_DB_URL: mongodb://mongo:27017/employees
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
